### ISSUE TITLE
Question: Return two thumbs of one image uploaded

### ISSUE THREAD

**Issue by modwebpl** [64j/multiFields#11]
I want to use only one large image but on web page I need to 3 different sizes same file.

Of course we can use "prepare" in Multifields and create "thumb" but it only assign 1 thumb to 1 uploaded image.

Can I upload one large file and create 2 or 3 different thumbs? (I don't want to create additional field to upload second image :/ )

**Comment by 64j** [comment]
prepare

```
$data['value.1'] = /* phpthumb for first image*/
$data['value.2'] = /* phpthumb for secondimage*/

return $data;
```

**Comment by modwebpl** [comment]
Thx, god bless u :).
