### ISSUE TITLE
Табличный вывод, проблема с ячейками

### ISSUE THREAD

**Issue by projkin** [64j/multiFields#23]
Как можно впихнуть в одну ячейку 2 разных поля: https://disk.yandex.ru/d/5bW3uA1bWpK3KQ
Я пробовал крутить конфигом уже 8 часов. Он не хочет в тип поля `'type' => 'table:td',`  давать возможность добавить, к примеру, картинку и текст. В документации тоже не нашел. Либо картинка, либо текст получается

**Comment by 64j** [comment]
Всё верно. Одна ячейка - один элемент

**Comment by projkin** [comment]
Спасибо за ответ. Очень жаль. =( Но в целом плагин всеравно хороший.
