### ISSUE TITLE
Database storing

### ISSUE THREAD

**Issue by modwebpl** [64j/multiFields#4]
Hello,

In protected method baseData() first line with sql make error:
$sql = $this->evo->db->query('SHOW TABLES FROM ' . $this->evo->db->config['dbase'] . ' LIKE "' . $this->evo->db->config['table_prefix'] . 'multifields"');

Error: "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIKE "ecuy_multifields"' at line 1"

this: die(var_dump($this->evo->db->config['dbase'])); return NULL o.0
I check params $this->eve->db->config and there is no "dbase" param.

it should be: $this->evo->db->config['database'])

**Comment by 64j** [comment]
What is your version of Evo?

https://github.com/evolution-cms/evolution/blob/1.4.x/manager/includes/extenders/dbapi.mysqli.class.inc.php#L35

**Comment by modwebpl** [comment]
In EVO 2.0 RC there is no parameter: $this->evo->db->config['dbase']) I change to: $this->evo->db->config['database']) and it works like a charm :).

**Comment by 64j** [comment]
@modwebpl 
Check, please

**Comment by sashabeep** [comment]
2.0 сегодняшний - тоже когда переключаешь на database та же ошибка
Версия сервера: 5.7.27-30-log что бы это ни значило

**« Evolution CMS Parse Error »
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIKE "multifields"' at line 1**

**Comment by sashabeep** [comment]
Причем, из консоли phpmyadmin такой запрос вручную работает
**SHOW TABLES FROM имябазы LIKE "%multifields%"** 

Попробовал переписать его в $sql - не получилось
