### ISSUE TITLE
How can I limit display only 1 elements if 3 was created - first, last or second ?

### ISSUE THREAD

**Issue by modwebpl** [64j/multiFields#8]
How can I limit display only 1 elements if 4 was created - first, last or second ?

**Comment by 64j** [comment]
When displaying elements, there is no limit on their display.
You can put your prepare handlers on output.

```
&prepare_Slider=`mf.prepare.Slider`
```

Snippet mf.prepare.Slider
```php
// $data, $modx, $_MF;

// all data
// $_MF->data


// $data[value] => assets/images/evo-logo.png
// $data[mf.parent] => 0
// $data[mf.name] => Slider
// $data[mf.level] => 1
// $data[mf.iteration] => 1

if ($data['mf.iteration'] == 1) {
    return;
}

return $data;
```

**Comment by modwebpl** [comment]
Thanks a lot for your answers.

I do what u said and now I have:

`{!! $modx->runSnippet('multifields', ['tvId' => '6', 'prepare_Slider' =>'mf.prepare.Slider', 'tpl_Slider' => '@FILE:views/chunks/prod-gal.blade.php']) !!}`

prod-gal.blade.php :

```
<div class="grid zoom--gal row mb10" data-src="[+image+]" data-zoom="[+zoom+]" data-scale="[+scale+]">
  <div class="border flex align-center">
    <img class="auto" src="[+image+]" alt="[+alt+]">
  </div>
</div>
```

snippet mf.prepare.Slider :

```
if ($data['mf.iteration'] == 1) {
    return;
}

return $data;
```

And from 3 multi fields I have blank html with [+alt+]

after prepare_Slider (it should be only one element):

![Zrzut ekranu 2020-03-2 o 11 44 03](https://user-images.githubusercontent.com/35030936/75669945-2e420480-5c7c-11ea-9c5c-90f988f55355.png)


before prepare_Slider (3 elements)

![Zrzut ekranu 2020-03-2 o 11 47 42](https://user-images.githubusercontent.com/35030936/75669821-fdfa6600-5c7b-11ea-8f76-cd79555eb48e.png)

Why it render blank html ?

**Comment by modwebpl** [comment]
Ok i figured it out, snippet mf.prepare.Slider:

```
if ($data['mf.iteration'] != 0) {
    return;
}
return $data;
```

and line 380 on assets/plugins/multifields/core/MultiFieldsFront.php I change:


`$out[$v['mf.name']] .= $this->tpl($tpl, $v);
`
to this:

`if(!count($out[$v])) $out[$v['mf.name']] .= $this->tpl($tpl, $v);
`

but we still need to get extra parameters like:

```
&display_key=`1` // will display only first item
&display_key=`3` // will display only third item etc.
```
